spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  circuitBreaker:
    instances:
      productService:
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
